# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python
build:
  os: ubuntu-22.04
  apt_packages: libmagic
  tools:
    python: "3.11"

# Build documentation in the docs/ directory
sphinx:
  configuration: docs/conf.py

# Declare the Python requirements required to build the docs
python:
  install:
    - requirements: docs/requirements.txt
