version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.7.6
    steps:
      - checkout
      - run:
          name: Install dev dependencies
          command: |
            python3 -m venv ~/venv
            . ~/venv/bin/activate
            make install
      - run:
          name: Test
          command: |
            . ~/venv/bin/activate
            make test
      - run:
          name: Lint
          command: |
            . ~/venv/bin/activate
            make lint
